services:
  dev-app:
    image: node:20
    working_dir: /app
    volumes:
      - ../../:/app
      - ../../node_modules:/app/node_modules
      - ../../dist:/app/dist
      - ../../public:/app/public
    command: bash -c "npm i --quiet --ignore-scripts && npm run start:dev"
    ports:
      - "3000:3000"
